name = "gays"
author = "all of you faggots"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "946e9b65a0fa0ffad2f5f5b46f40608bacb3bed07ed906e3e7f393b68b83c648"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
