name = "gays"
author = "all of you faggots"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "441cc90b6f210923c7c7dff186af42d6148673ea7dd93a5d706357266cb7d1c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
